server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE  
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true   
       
       
       
       
       
       
       
       